name: Checks

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: clippy
          toolchain: nightly
          command: cargo clippy --all-targets --all-features -- --deny warnings            
        - name: rustdoc
          toolchain: "1.98"
          command: RUSTDOCFLAGS="--document-private-items --deny warnings" cargo doc
        - name: rustfmt
          toolchain: "1.98"
          command: cargo fmt --check -- `find . -name "*.rs"`
        - name: test-nightly
          toolchain: nightly
          command: cargo test --features simd
        - name: test-stable
          toolchain: "1.98"
          command: cargo test
    steps:
    - uses: actions/checkout@v7
    - run: rustup install ${{ matrix.toolchain }} --profile default
    - run: rustup default ${{ matrix.toolchain }}
    - run: ${{ matrix.command }}
